
- name: Reload user systemd daemon
  systemd:
    daemon_reload: true
    scope: user

- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: true
    scope: system

- name: Restart protonwire if changed
  become: true
  systemd:
    state: restarted
    name: protonwire
  when: protonwire_container.changed

- name: Start protonwire if not changed
  become: true
  systemd:
    state: started
    name: protonwire
  when: not protonwire_container.changed