- name: Start caddy
  become: true
  systemd:
    name: testvpn
    state: started

- name: Fetch VPN IP address
  uri:
    url: 'http://localhost:{{ wireguard.ports.caddy }}'
    method: GET
    return_content: true
  register: vpn_ip_result

- name: Fetch home IP address
  uri:
    url: https://ip.me
    method: GET
    return_content: true
  register: home_ip_result

- name: Validate IP address is different from home IP
  assert:
    that:
      - vpn_ip_result.content != home_ip_result.content
    fail_msg: "The returned IP address does not differ from home."