apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: application-api-keys-secret
  namespace: media-server
  labels:
    helm.sh/chart: media-server-0.1.0
    app.kubernetes.io/name: media-server
    app.kubernetes.io/instance: media-server
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: SecretStore
  target:
    name: application-api-keys
    creationPolicy: Owner
  data:
  - secretKey: SONARR_API_KEY
    remoteRef:
      key: /api-keys/SONARR_API_KEY
  - secretKey: RADARR_API_KEY
    remoteRef:
      key: /api-keys/RADARR_API_KEY
  - secretKey: PROWLARR_API_KEY
    remoteRef:
      key: /api-keys/PROWLARR_API_KEY