- name: Caddyfile
  become: true
  tags:
    - become
  template:
    src: ../templates/Caddyfile.j2
    dest: '{{ caddy_config }}'
  notify: restart_caddy

- name: users.json.j2
  become: true
  template:
  tags:
    - become
    src: ../templates/users.json.j2
    dest: '{{ caddy_users }}'
  notify: restart_caddy

- name: caddy.container
  become: true
  tags:
    - become
  template:
    src: ../templates/caddy.container.j2
    dest: '{{ containers.unit.system }}/caddy.container'
  notify: restart_caddy

- name: data caddy
  become: true
  tags:
    - become
  file:
    path: '{{ caddy_data }}'
    state: directory

- community.general.ufw:
    rule: allow
    port: 8090
  become: true
  tags:
    - become
  name: Allow HTTP 8090

- community.general.ufw:
    rule: allow
    port: https
  become: true
  tags:
    - become
  name: Allow HTTPS