- name: create radarr_config
  become: true
  file:
    path: '{{ radarr_config }}'
    state: directory
    recurse: true
    owner: '{{ ansible_user }}'
    group: '{{ ansible_group }}'

- template:
    src: '../templates/radarr.container.j2'
    dest: '{{ containers.unit.user }}/radarr.container'
  notify: restart_radarr

