- name: create radarr_config
  file:
    path: '{{ radarr_config }}'
    state: directory

- template:
    src: '../templates/radarr.container.j2'
    dest: '{{ containers.unit.user }}/radarr.container'
  notify: restart_radarr

