- name: create sonarr_config
  become: true
  tags:
    - become
  file:
    path: '{{ sonarr_config }}'
    state: directory
    recurse: true
    owner: '{{ ansible_user }}'
    group: '{{ ansible_group }}'

- template:
    src: '../templates/sonarr.container.j2'
    dest: '{{ containers.unit.user }}/sonarr.container'
  notify: restart_sonarr

