apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 2h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
    namespace: external-secrets
  target:
    name: tailscale
    creationPolicy: Owner
  data:
    - secretKey: AUTH_KEY
      remoteRef:
        key: /tailscale/AUTH_KEY