{{- if .Values.flaresolverr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "media-server.fullname" . }}-flaresolverr
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
    {{- include "media-server.componentLabels" "flaresolverr" | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "media-server.selectorLabels" . | nindent 6 }}
      {{- include "media-server.componentLabels" "flaresolverr" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "media-server.selectorLabels" . | nindent 8 }}
        {{- include "media-server.componentLabels" "flaresolverr" | nindent 8 }}
    spec:
      securityContext:
        {{- include "media-server.securityContext" . | nindent 8 }}
      containers:
      - name: flaresolverr
        image: {{ .Values.flaresolverr.image }}
        ports:
        - containerPort: {{ .Values.flaresolverr.port }}
          name: http
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_HTML
          value: "false"
        - name: CAPTCHA_SOLVER
          value: "none"
        resources:
          {{- toYaml .Values.flaresolverr.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
{{- end }}