{{- if .Values.flaresolverr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "media-server.fullname" . }}-flaresolverr
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
    {{- include "media-server.componentLabels" "flaresolverr" | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.flaresolverr.port }}
    targetPort: http
    name: http
  selector:
    {{- include "media-server.selectorLabels" . | nindent 4 }}
    {{- include "media-server.componentLabels" "flaresolverr" | nindent 4 }}
{{- end }}