- name: Login to dockerhub
  containers.podman.podman_login:
    username: '{{ private.docker_hub_user }}'
    password: '{{ private.docker_hub_token }}'

- name: Create root quadlet directory
  become: true
  tags:
    - become
  file:
    path: '{{ containers.unit.system }}'
    state: directory

- name: Create quadlet directory
  file:
    path: '{{ containers.unit.user }}'
    state: directory

- name: Enable lingering
  become: true
  tags:
    - become
  command: 'loginctl enable-linger {{ ansible_user }}'