- name: Copy container-compose.yml
  ansible.builtin.template:
    src: ../files/container-compose.yml
    dest: '{{ containers.directory }}/container-compose.yml'

- name: Run container-compose
  community.docker.docker_compose:
    state: present
    project_src: '{{ containers.directory }}'
    files:
     - container-compose.yml
