- name: Create wireguard secret
  containers.podman.podman_secret:
    state: present
    name: '{{ wireguard.secret_name }}'
    data: '{{ private.proton_key }}'

- name: Install protonwire.container
  template:
    src: ../files/protonwire.container.j2
    dest: $HOME/.config/containers/systemd/protonwire.container

- name: Install testvpn.service
  template:
    src: ../files/testvpn.service.j2
    dest: $HOME/.config/containers/systemd/testvpn.service

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
    user: true

- name: Start testvpn service
  systemd:
    state: started
    name: testvpn.service
    user: true