apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 2h0m0s
  chart:
    spec:
      chart: external-secrets
      version: 0.19.1
      sourceRef:
        kind: HelmRepository
        name: external-secrets-repo
        namespace: flux-system
  install:
    createNamespace: true
  values:
    extraArgs:
      enable-managed-secrets-caching: false