apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 2h
  path: "./clusters/media-server/external-secrets"
  prune: true
  wait: true