apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 2h
  path: ./clusters/media-server/external-secrets
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: media-server-repo
    namespace: flux-system
  dependsOn:
    - name: flux-system