services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VERSION=docker
    volumes:
      - '{{ data.library.tvshows.path }}:/tv'
      - '{{ data.library.movies.path }}:/movies'
      - '{{ data.library.config.path }}:/config'
# {% if enable_quicksync %}
    devices:
      - /dev/dri:/dev/dri
# {% endif %}