# Default values for media-server
# This is a YAML-formatted file.

# Global configuration
namespace: media-server
# Infisical configuration for External Secrets
infisical:
  projectId: media-server
  environment: dev
global:
  libraryPath: invalid
  downloadsPath: invalid
  downloadsMount: /downloads
# Plex Media Server
plex:
  image: ghcr.io/home-operations/plex:1.43.1@sha256:a9c3723cb31cc9621df27cf5801184c290293adf1df2bfaea4b8b6fc01dbfd96 # {"$imagepolicy": "media-server:plex"}
  advertiseIp: invalid
qbittorrent:
  image: ghcr.io/linuxserver/qbittorrent:5.2.0_v2.0.12-ls457@sha256:f76c4363cce0834df43b097682928d217f9f0e0fa1d13781c0934848d543e4ab # {"$imagepolicy": "media-server:qbittorrent"}
  webUiPort: 13000
qui:
  image: ghcr.io/autobrr/qui:v1.18.0@sha256:2e768c8509831afd1f606d27d9aa8e5f3fc722fac4ea88acfdc4fa3b0e9b13ae # {"$imagepolicy": "media-server:qui"}
gluetun:
  image: qmcgaw/gluetun:v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab # {"$imagepolicy": "media-server:gluetun"}
samba:
  image: ghcr.io/dockur/samba:4.23.7@sha256:0272e81926b285f868863691d6bf711812a3da3b8845d48b35a2093c068fb0ee # {"$imagepolicy": "media-server:samba"}
sonarr:
  image: ghcr.io/home-operations/sonarr:4.0.17@sha256:4ff5667a371e08b098858fa2457a99a5fef5f6a32640eb8567efe979d13ac9fc # {"$imagepolicy": "media-server:sonarr"}
tailscale:
  image: docker.io/tailscale/tailscale:v1.96.5@sha256:dbeff02d2337344b351afac203427218c4d0a06c43fc10a865184063498472a6 # {"$imagepolicy": "media-server:tailscale"}
prowlarr:
  image: ghcr.io/home-operations/prowlarr:2.3.7@sha256:b9557d772c974901aed9285189d904b613f1f07750fca930eecfe78544bd3d48 # {"$imagepolicy": "media-server:prowlarr"}
radarr:
  image: ghcr.io/home-operations/radarr:5.27.3@sha256:1bf822eaf3d944dc994656c3a712a89df0d88f5f46731af4fccc90c5e0333167 # {"$imagepolicy": "media-server:radarr"}
byparr:
  image: ghcr.io/thephaseless/byparr:latest@sha256:ec84210e7b91549c89eaf883a7bc71f84b9d3ffef3c198cc001220e1dd4bc360 # {"$imagepolicy": "media-server:byparr"}
