# Default values for media-server
# This is a YAML-formatted file.

# Global configuration
namespace: media-server
# Infisical configuration for External Secrets
infisical:
  projectId: media-server
  environment: dev
global:
  libraryPath: invalid
  downloadsPath: invalid
  downloadsMount: /downloads
# Plex Media Server
plex:
  image: ghcr.io/home-operations/plex:1.43.2@sha256:be00a2ad851ea3193cd870636f908eb6425ad89390f23cdb08daa35ab5cceacc # {"$imagepolicy": "media-server:plex"}
  advertiseIp: invalid
qbittorrent:
  image: ghcr.io/linuxserver/qbittorrent:5.2.3_v2.0.13-ls468@sha256:352371a7242e8b4aa10958ca02076d1023758070519b89a10251475fb9f1a35a # {"$imagepolicy": "media-server:qbittorrent"}
  webUiPort: 13000
qui:
  image: ghcr.io/autobrr/qui:v1.23.0@sha256:b1abd18f1d544cd5c63a3b8d9c8a91d097143e04df416567a8cb52040f380ca8 # {"$imagepolicy": "media-server:qui"}
gluetun:
  image: qmcgaw/gluetun:v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab # {"$imagepolicy": "media-server:gluetun"}
samba:
  image: ghcr.io/dockur/samba:4.23.8@sha256:660d15a568e0c04bc9c2b49df09183ab2bf22b129e6541fda6f823875e0a8500 # {"$imagepolicy": "media-server:samba"}
sonarr:
  image: ghcr.io/home-operations/sonarr:4.0.18@sha256:2cd77fb3d81909a734d61bb8f71462044cb9d2f187e626a28a05a5c4e4be8fd2 # {"$imagepolicy": "media-server:sonarr"}
tailscale:
  image: docker.io/tailscale/tailscale:v1.98.8@sha256:d54b2e6a9c09f0e5ec52e82b9ad4af3d446b54a7c08075e92f11c39dd410105f # {"$imagepolicy": "media-server:tailscale"}
prowlarr:
  image: ghcr.io/home-operations/prowlarr:2.5.1@sha256:5014bec2085b72759570ae958cdee251956c059bf82ca6244a3ce99e1c327a12 # {"$imagepolicy": "media-server:prowlarr"}
  webUiPort: 9696
radarr:
  image: ghcr.io/home-operations/radarr:6.2.1.10461@sha256:a566e7d364b96ce8ffb1b582266e656c69f3a12dec289d72bb0daa647ed4725e # {"$imagepolicy": "media-server:radarr"}
