# Default values for media-server
# This is a YAML-formatted file.

# Global configuration
namespace: media-server
# Infisical configuration for External Secrets
infisical:
  projectId: media-server
  environment: dev
global:
  libraryPath: invalid
  downloadsPath: invalid
  downloadsMount: /downloads
# Plex Media Server
plex:
  image: ghcr.io/home-operations/plex:1.43.1@sha256:a9c3723cb31cc9621df27cf5801184c290293adf1df2bfaea4b8b6fc01dbfd96 # {"$imagepolicy": "media-server:plex"}
  advertiseIp: invalid
qbittorrent:
  image: ghcr.io/linuxserver/qbittorrent:5.1.4-r2-ls448@sha256:a89108b1bf43de072a35a59a3ee41b97b564538faae5cbb3f6c803aa7f5fd9f7 # {"$imagepolicy": "media-server:qbittorrent"}
  webUiPort: 13000
qui:
  image: ghcr.io/autobrr/qui:v1.16.1@sha256:07b6ea9572e52e8b5f70f8fb15a7c688d8d754a7616242d3ad0b21dbd5c05836 # {"$imagepolicy": "media-server:qui"}
gluetun:
  image: qmcgaw/gluetun:v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab # {"$imagepolicy": "media-server:gluetun"}
samba:
  image: ghcr.io/dockur/samba:4.23.5@sha256:63428d1cb6c1ace60cfa782c1d6c9e4b3686044fc47600c97055e6b62e9bb5fa # {"$imagepolicy": "media-server:samba"}
sonarr:
  image: ghcr.io/home-operations/sonarr:4.0.17@sha256:83607d2b741ec9469db09489e88c473ae6fdf7d85f3b55d4fa809b43e25a2a6c # {"$imagepolicy": "media-server:sonarr"}
tailscale:
  image: docker.io/tailscale/tailscale:v1.96.5@sha256:dbeff02d2337344b351afac203427218c4d0a06c43fc10a865184063498472a6 # {"$imagepolicy": "media-server:tailscale"}
prowlarr:
  image: ghcr.io/home-operations/prowlarr:2.3.5@sha256:fc87e9af2f175ef19610fdcf1fcdcc84d5099127211cc6733f826409b2733237 # {"$imagepolicy": "media-server:prowlarr"}
radarr:
  image: ghcr.io/home-operations/radarr:5.27.3@sha256:1bf822eaf3d944dc994656c3a712a89df0d88f5f46731af4fccc90c5e0333167 # {"$imagepolicy": "media-server:radarr"}
byparr:
  image: ghcr.io/thephaseless/byparr:latest@sha256:ec84210e7b91549c89eaf883a7bc71f84b9d3ffef3c198cc001220e1dd4bc360 # {"$imagepolicy": "media-server:byparr"}
