apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: {{ .Values.namespace }}
  labels:
    app: samba
spec:
  type: NodePort
  ports:
    - port: 445
      targetPort: 445
      nodePort: 445
      name: smb
      protocol: TCP
  selector:
    app: samba