
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets-repo
  namespace: external-secrets
spec:
  url: https://charts.external-secrets.io
  interval: 1h0m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 2h0m0s
  chart:
    spec:
      chart: external-secrets
      version: 0.19.1
      sourceRef:
        kind: HelmRepository
        name: external-secrets-repo
  values:
    extraArgs:
      enable-managed-secrets-caching: false
