


---
apiVersion: v1
kind: Namespace
metadata:
  name: intel
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel
  namespace: intel
spec:
  url: https://intel.github.io/helm-charts/
  interval: 1h0m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel
  namespace: intel
spec:
  releaseName: dp-operator
  chart:
    spec:
      chart: intel-device-plugins-operator
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: intel
  interval: 2h
  install:
    createNamespace: true
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu
  namespace: intel
spec:
  releaseName: gpu
  chart:
    spec:
      chart: intel-device-plugins-gpu
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: intel
  interval: 2h
  install:
    createNamespace: true
  values: {}