apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: media-server
  namespace: media-server
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux-bot
        email: flux-bot@example.com
      messageTemplate: |
        update {{range .Updated.Images}}{{.Name}}:{{.CurrentTag}} → {{.NewTag}}{{"\n"}}{{end}}
    push:
      branch: main
  update:
    path: ./charts/media-server
    strategy: Setters
