apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-server
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/media-server/media-server
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: media-server-repo
    namespace: flux-system