apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: https://mojo2600.github.io/pihole-kubernetes/
      sourceRef:
        kind: HelmRepository
        name: pihole
      reconcileStrategy: Revision
  values:
    # Default values for pihole.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.

    # -- The number of replicas
    replicaCount: 1

    # -- The `spec.strategyTpye` for updates
    strategyType: RollingUpdate

    # -- The maximum number of Pods that can be created over the desired number of `ReplicaSet` during updating.
    maxSurge: 1

    # -- The maximum number of Pods that can be unavailable during updating
    maxUnavailable: 1

    # -- The number of old ReplicaSets to retain to allow rollback
    revisionHistoryLimit: 10

    image:
      # -- the repostory to pull the image from
      repository: "pihole/pihole"
      # -- the docker tag, if left empty it will get it from the chart's appVersion
      tag: ""
      # -- the pull policy
      pullPolicy: IfNotPresent

    dualStack:
      # -- set this to true to enable creation of DualStack services or creation of separate IPv6 services if `serviceDns.type` is set to `"LoadBalancer"`
      enabled: false

    dnsHostPort:
      # -- set this to true to enable dnsHostPort
      enabled: false
      # -- default port for this pod
      port: 53

    # -- Configuration for the DNS service on port 53
    serviceDns:
      # -- deploys a mixed (TCP + UDP) Service instead of separate ones
      mixedService: false

      # -- `spec.type` for the DNS Service
      type: NodePort

      # -- The port of the DNS service
      port: 53

      # -- Optional node port for the DNS service
      nodePort: ""

      # -- `spec.externalTrafficPolicy` for the DHCP Service
      externalTrafficPolicy: Local

      # -- A fixed `spec.loadBalancerIP` for the DNS Service
      loadBalancerIP: ""
      # -- A fixed `spec.loadBalancerIP` for the IPv6 DNS Service
      loadBalancerIPv6: ""
      # -- `spec.loadBalancerClass` for the DNS Service. Only used if type is LoadBalancer.
      loadBalancerClass: ""

      # -- Annotations for the DNS service
      annotations: { }

      # -- Labels for the DNS service
      extraLabels:
        { }

    # -- Configuration for the DHCP service on port 67
    serviceDhcp:
      # -- Generate a Service resource for DHCP traffic
      enabled: false
    # -- Configuration for the web interface service
    serviceWeb:
      # -- Configuration for the HTTP web interface listener
      http:
        # -- Generate a service for HTTP traffic
        enabled: true

        # -- The port of the web HTTP service
        port: 80

        # -- Optional node port for the web HTTP service
        nodePort: ""

      # -- Configuration for the HTTPS web interface listener
      https:
        # -- Generate a service for HTTPS traffic
        enabled: false

      # -- `spec.type` for the web interface Service
      type: ClusterIP

      # -- `spec.externalTrafficPolicy` for the web interface Service
      externalTrafficPolicy: Local

      # -- A fixed `spec.loadBalancerIP` for the web interface Service
      loadBalancerIP: ""
      # -- A fixed `spec.loadBalancerIP` for the IPv6 web interface Service
      loadBalancerIPv6: ""
      # -- `spec.loadBalancerClass` for the web interface Service. Only used if type is LoadBalancer.
      loadBalancerClass: ""

      # -- Annotations for the DHCP service
      annotations: { }
      # metallb.universe.tf/address-pool: network-services
      # metallb.universe.tf/allow-shared-ip: pihole-svc

      # -- Labels for the web interface service
      extraLabels:
        { }

    virtualHost: pi.hole

    # -- Configuration for the Ingress
    ingress:
      # -- Generate a Ingress resource
      enabled: false

    # -- Probes configuration
    probes:
      # -- probes.liveness -- Configure the healthcheck for the ingress controller
      liveness:
        # -- Generate a liveness probe
        # 'type' defaults to command, can be set to 'httpGet' to use a HTTP GET type liveness probe.
        type: command
        command:
          - /bin/sh
          - -c
          - "curl --silent http://localhost/api/info/login | jq 'if (.dns | not) then halt_error(1) end'"
        enabled: true
        # -- wait time before trying the liveness probe
        initialDelaySeconds: 60
        # -- threshold until the probe is considered failing
        failureThreshold: 10
        # -- timeout in seconds
        timeoutSeconds: 5
        # port: http
        # scheme: HTTP
      readiness:
        # -- Generate a readiness probe
        # 'type' defaults to command, can be set to 'httpGet' to use a HTTP GET type readiness probe.
        type: command
        command:
          - /bin/sh
          - -c
          - "curl --silent http://localhost/api/info/login | jq 'if (.dns | not) then halt_error(1) end'"
        enabled: true
        # -- wait time before trying the readiness probe
        initialDelaySeconds: 60
        # -- threshold until the probe is considered failing
        failureThreshold: 10
        # -- timeout in seconds
        timeoutSeconds: 5
        # port: http
        # scheme: HTTP

    # -- We usually recommend not to specify default resources and to leave this as a conscious
    # -- choice for the user. This also increases chances charts run on environments with little
    # -- resources, such as Minikube. If you do want to specify resources, uncomment the following
    # -- lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    resources:
       limits:
        cpu: 100m
        memory: 128Mi
      # requests:
    #  cpu: 100m
    #  memory: 128Mi

    # -- `spec.PersitentVolumeClaim` configuration
    persistentVolumeClaim:
      # -- set to true to use pvc
      enabled: true

      # -- specify an existing `PersistentVolumeClaim` to use
      # existingClaim: ""

      # -- Annotations for the `PersitentVolumeClaim`
      annotations: { }

      accessModes:
        - ReadWriteOnce

      # -- volume claim size
      size: "500Mi"

      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"

      ## If subPath is set mount a sub folder of a volume instead of the root of the volume.
      ## This is especially handy for volume plugins that don't natively support sub mounting (like glusterfs).

      ## subPath: "pihole"

    # -- Node selector values
    nodeSelector: { }

    # -- Toleration
    tolerations: [ ]

    # -- Specify a priorityClassName
    # priorityClassName: ""

    # Reference: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
    topologySpreadConstraints: [ ]
    # - maxSkew: <integer>
    #   topologyKey: <string>
    #   whenUnsatisfiable: <string>
    #   labelSelector: <object>

    affinity: { }

    # -- Administrator password when not using an existing secret (see below)
    adminPassword: "admin"

    # -- Use an existing secret for the admin password.
    admin:
      # -- If set to false admin password will be disabled, adminPassword specified above and the pre-existing secret (if specified) will be ignored.
      enabled: true
      # -- Specify an existing secret to use as admin password
      existingSecret: ""
      # -- Specify the key inside the secret to use
      passwordKey: "password"
      # -- Specify [annotations](docs/Values.md#admin.annotations) to be added to the secret
      annotations:
      # reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      # reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "external-dns"

    # -- extraEnvironmentVars is a list of extra enviroment variables to set for pihole to use. You can use either scalars or project cm, secrets or pod fields via valueFrom
    extraEnvVars:
      # issue 360
      FTLCONF_dns_listeningMode: 'all'
      # TZ: UTC
      # Project a variable
      # SOME_VAR:
      #   valueFrom:
      #     configMapKeyRef:
      #       key: some-var
      #       name: my-config-map

    # -- extraEnvVarsSecret is a list of secrets to load in as environment variables.
    extraEnvVarsSecret: { }
      # env_var:
    #   name: secret-name
    #   key: secret-key

    # -- default upstream DNS 1 server to use
    DNS1: "8.8.8.8"
    # -- default upstream DNS 2 server to use
    DNS2: "8.8.4.4"

    antiaff:
      # -- set to true to enable antiaffinity (example: 2 pihole DNS in the same cluster)
      enabled: false

    doh:
      # -- set to true to enabled DNS over HTTPs via cloudflared
      enabled: false
    # -- DNS MASQ settings
    dnsmasq:
      # -- Load custom user configuration files from /etc/dnsmasq.d
      enableCustomDnsMasq: true

      # -- Add upstream dns servers. All lines will be added to the pihole dnsmasq configuration
      upstreamServers: [ ]
      # - server=/foo.bar/192.168.178.10
      # - server=/bar.foo/192.168.178.11

      # -- Add custom dns entries to override the dns resolution. All lines will be added to the pihole dnsmasq configuration.
      customDnsEntries: [ ]
      # - address=/foo.bar/192.168.178.10
      # - address=/bar.foo/192.168.178.11

      # -- Dnsmasq reads the /etc/hosts file to resolve ips. You can add additional entries if you like
      additionalHostsEntries: [ ]
      # - 192.168.0.3     host4
      # - 192.168.0.4     host5

      # -- Static DHCP config
      staticDhcpEntries: [ ]
      # staticDhcpEntries:
      # - dhcp-host=MAC_ADDRESS,IP_ADDRESS,HOSTNAME

      # -- Other options
      customSettings:
      # otherSettings: |
      #   rebind-domain-ok=/plex.direct/

      # -- Here we specify custom cname entries that should point to `A` records or
      # elements in customDnsEntries array.
      # The format should be:
      #  - cname=cname.foo.bar,foo.bar
      #  - cname=cname.bar.foo,bar.foo
      #  - cname=cname record,dns record
      customCnameEntries: [ ]
      # Here we specify custom cname entries that should point to `A` records or
      # elements in customDnsEntries array.
      # The format should be:
      #   - cname=cname.foo.bar,foo.bar
      #   - cname=cname.bar.foo,bar.foo
      #   - cname=cname record,dns record

    # -- list of adlists to import during initial start of the container
    adlists:
      - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
      - https://v.firebog.net/hosts/static/w3kbl.txt
      - https://adaway.org/hosts.txt
      - https://v.firebog.net/hosts/AdguardDNS.txt
      - https://v.firebog.net/hosts/Admiral.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://v.firebog.net/hosts/Easylist.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
      - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
      - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
      - https://v.firebog.net/hosts/Prigent-Crypto.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
      - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
      - https://phishing.army/download/phishing_army_blocklist_extended.txt
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
      - https://v.firebog.net/hosts/RPiList-Malware.txt
      - https://v.firebog.net/hosts/RPiList-Phishing.txt
      - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
      - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
      - https://urlhaus.abuse.ch/downloads/hostfile/
      - https://lists.cyberhost.uk/malware.txt
      # If you want to provide blocklists, add them here.
    # - https://hosts-file.net/grm.txt
    # - https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts

    # -- list of whitelisted domains to import during initial start of the container
    whitelist: { }
    # If you want to provide whitelisted domains, add them here.
    # - clients4.google.com

    # -- list of blacklisted domains to import during initial start of the container
    blacklist: { }
    # If you want to have special domains blacklisted, add them here
    # - *.blackist.com

    # -- list of blacklisted regex expressions to import during initial start of the container
    regex: { }
    # Add regular expression blacklist items
    # - (^|\.)facebook\.com$

    # -- values that should be added to pihole-FTL.conf. You can use either scalars or project cm, secrets or pod fields via valueFrom
    ftl: { }
      # Add values for pihole-FTL.conf
      # MAXDBDAYS: 14
      # Project a variable
      # LOCAL_IPV4:
      #   valueFrom:
    #     fieldRef:
    #       fieldPath: status.podIP

    # -- port the container should use to expose HTTP traffic
    webHttp: "80"

    # -- port the container should use to expose HTTPS traffic
    webHttps: "443"

    # -- hostname of pod
    hostname: ""

    # -- should the container use host network
    hostNetwork: "false"

    # -- should container run in privileged mode
    privileged: "false"

    # linux capabilities container should run with
    capabilities: { }
    # add:
    # - NET_ADMIN

    customVolumes:
      # -- set this to true to enable custom volumes
      enabled: false
      # -- any volume type can be used here
      config: { }
      # hostPath:
      #   path: "/mnt/data"

    # -- any extra volumes you might want
    extraVolumes: { }
      # external-conf:
    #   configMap:
    #     name: pi-hole-lighttpd-external-conf

    # -- any extra volume mounts you might want
    extraVolumeMounts: { }
      # external-conf:
    #   mountPath: /etc/lighttpd/external.conf
    #   subPath: external.conf

    extraContainers: [ ]

    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 8.8.8.8
