---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: plex
  namespace: media-server
spec:
  image: ghcr.io/home-operations/plex
  interval: 2h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: plex
  namespace: media-server
spec:
  imageRepositoryRef:
    name: plex
  # ensure digests are reflected in status so automation can write them into Git
  digestReflectionPolicy: Always
  interval: 2h
  policy:
    semver:
      # you asked for caret-prefixed ranges; this keeps us on major 1, compatible style
      range: '^1.42.1'
