---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: prowlarr
  namespace: media-server
spec:
  image: ghcr.io/home-operations/prowlarr
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: prowlarr
  namespace: media-server
spec:
  imageRepositoryRef:
    name: prowlarr
  digestReflectionPolicy: Always
  interval: 1h
  # no filterTags (non-linuxserver image)
  policy:
    semver:
      range: '^2.0.3'
