---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: qbittorrent
  namespace: media-server
spec:
  image: ghcr.io/linuxserver/qbittorrent
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: qbittorrent
  namespace: media-server
spec:
  imageRepositoryRef:
    name: qbittorrent
  digestReflectionPolicy: IfNotPresent
  filterTags:
    # capture numeric version and ls suffix, e.g. "5.1.2-r1-ls408" -> ver=5.1.2 ls=ls408
    pattern: '^(?P<ver>\d+\.\d+\.\d+).*-(?P<ls>ls\d+)$'
    extract: '$ver-$ls'
  policy:
    semver:
      # caret-style range that keeps us on major 5 (compatible updates)
      range: '^5.1.2-0'
