---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: sonarr
  namespace: media-server
spec:
  image: ghcr.io/home-operations/sonarr
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sonarr
  namespace: media-server
spec:
  imageRepositoryRef:
    name: sonarr
  digestReflectionPolicy: Always
  # NO filterTags — treat full tag as the version string
  policy:
    semver:
      # anchored to the current chart version you provided:
      range: '^4.0.15.2940'
