apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-plugin
  namespace: inteldeviceplugins-system
spec:
  interval: 4h0m0s
  chart:
    spec:
      chart: intel-device-plugins-gpu
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  install:
    createNamespace: true
  values:
    nodeFeatureRule: false
