{{- if .Values.prowlarr.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "media-server.fullname" . }}-prowlarr-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
    {{- include "media-server.componentLabels" "prowlarr" | nindent 4 }}
data:
  config.xml: |
    <Config>
      <BindAddress>*</BindAddress>
      <Port>{{ .Values.prowlarr.port }}</Port>
      <SslPort>6969</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>False</LaunchBrowser>
      <ApiKey>${PROWLARR_API_KEY}</ApiKey>
      <AuthenticationMethod>{{ .Values.prowlarr.config.authenticationMethod | default "Forms" }}</AuthenticationMethod>
      <AuthenticationRequired>{{ .Values.prowlarr.config.authenticationRequired | default "Enabled" }}</AuthenticationRequired>
      <Branch>master</Branch>
      <LogLevel>{{ .Values.prowlarr.config.logLevel | default "info" }}</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase>{{ .Values.prowlarr.config.urlBase | default "" }}</UrlBase>
      <InstanceName>{{ .Values.prowlarr.config.instanceName | default "Prowlarr" }}</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
      {{- if .Values.prowlarr.config.username }}
      <Username>${PROWLARR_USERNAME}</Username>
      {{- end }}
      {{- if .Values.prowlarr.config.password }}
      <Password>${PROWLARR_PASSWORD}</Password>
      {{- end }}
    </Config>
{{- end }}