apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      name: prowlarr
      labels:
        app: prowlarr
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      dnsPolicy: "ClusterFirstWithHostNet"
      dnsConfig:
        nameservers:
          - 9.9.9.9
          - 149.112.112.112
      containers:
        - name: prowlarr
          image: {{ .Values.prowlarr.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9696
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: prowlarr-config
          env:
            - name: PROWLARR__API_KEY
              valueFrom:
                secretKeyRef:
                  name: prowlarr-secret
                  key: API_KEY
          startupProbe:
            httpGet:
              port: 9696
              path: "/healthz"
            initialDelaySeconds: 5
            failureThreshold: 6
            periodSeconds: 5
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              port: 9696
              path: "/healthz"
            periodSeconds: 720
            failureThreshold: 3
      volumes:
        - name: prowlarr-config
          hostPath:
            path: /var/lib/prowlarr
            type: DirectoryOrCreate

