apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      name: prowlarr
      labels:
        app: prowlarr
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 9.9.9.9
          - 149.112.112.112
          - 10.96.0.10
        searches:
          - {{ .Values.namespace }}.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "1"
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        # - name: gluetun
        #   image:  {{ .Values.gluetun.image }}
        #   securityContext:
        #     runAsUser: 0
        #     privileged: true
        #     capabilities:
        #       add: [ "NET_ADMIN" ]
        #   livenessProbe:
        #     timeoutSeconds: 10
        #     failureThreshold: 5
        #     periodSeconds: 720
        #     initialDelaySeconds: 5
        #     exec:
        #       command: [ "/gluetun-entrypoint", "healthcheck" ]
        #   env:
        #     - name: TZ
        #       value: "Europe/Paris"
        #     - name: FIREWALL_INPUT_PORTS
        #       value: "{{ .Values.prowlarr.webUiPort }}"
        #     - name: SERVER_COUNTRIES
        #       value: "Netherlands"
        #     - name: VPN_SERVICE_PROVIDER
        #       value: "protonvpn"
        #     - name: DNS_KEEP_NAMESERVER
        #       value: "off"
        #     - name: DOT
        #       value: "off"
        #     - name: VPN_TYPE
        #       value: "wireguard"
        #     - name: WIREGUARD_PRIVATE_KEY
        #       valueFrom:
        #         secretKeyRef:
        #           name: protonvpn-credentials
        #           key: PROTONVPN_PRIVATE_KEY
        - name: prowlarr
          image: {{ .Values.prowlarr.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.prowlarr.webUiPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: prowlarr-config
          env:
            - name: PROWLARR__API_KEY
              valueFrom:
                secretKeyRef:
                  name: prowlarr-secret
                  key: API_KEY
          startupProbe:
            httpGet:
              port: {{ .Values.prowlarr.webUiPort }}
              path: "/healthz"
            initialDelaySeconds: 5
            failureThreshold: 6
            periodSeconds: 5
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              port: {{ .Values.prowlarr.webUiPort }}
              path: "/healthz"
            periodSeconds: 720
            failureThreshold: 3
      volumes:
        - name: prowlarr-config
          hostPath:
            path: /var/lib/prowlarr
            type: DirectoryOrCreate

