apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 2h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: prowlarr-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: /api-keys/PROWLARR_API_KEY