apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 19m
  path: ./clusters/media-server/flux-systen
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: media-server-repo
    namespace: flux-system