---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: {{ .Values.namespace }}
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: gluetun
          image:  {{ .Values.gluetun.image }}
          securityContext:
            privileged: true
            capabilities:
              add: [ "NET_ADMIN" ]
          readinessProbe:
            timeoutSeconds: 10
            failureThreshold: 5
            periodSeconds: 720
            initialDelaySeconds: 15
            exec:
              command: [ "/gluetun-entrypoint", "healthcheck" ]
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: FIREWALL_INPUT_PORTS
              value: "{{ .Values.qbittorrent.webUiPort }}"
            - name: SERVER_COUNTRIES
              value: "France"
            - name: VPN_SERVICE_PROVIDER
              value: "protonvpn"
            - name: DNS_KEEP_NAMESERVER
              value: "off"
            - name: DOT
              value: "off"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: protonvpn-credentials
                  key: PROTONVPN_PRIVATE_KEY
            - name: PORT_FORWARD_ONLY
              value: "on"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: VPN_PORT_FORWARDING_UP_COMMAND
              value: >
                /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":\{\{PORTS\}\}}" http://127.0.0.1:{{ .Values.qbittorrent.webUiPort }}/api/v2/app/setPreferences 2>&1'
        - name: qbittorrent
          image: {{ .Values.qbittorrent.image }}
          ports:
            - containerPort: {{ .Values.qbittorrent.webUiPort }}
              name: qbt-web
              protocol: TCP
            - containerPort: {{ .Values.qbittorrent.torrentPort }}
              name: qbt-torrent
              protocol: UDP
          env:
            - name: TZ
              value: Europe/Paris
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: WEBUI_PORT
              value: "{{ .Values.qbittorrent.webUiPort }}"
            - name: TORRENTING_PORT
              value: "{{ .Values.qbittorrent.torrentPort }}"
          volumeMounts:
            - name: app-downloads
              mountPath: {{ .Values.global.downloadsMount }}
            - name: config
              mountPath: /config
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "6Gi"
              cpu: "4000m"
      volumes:
        - name: app-downloads
          hostPath:
            path: {{ .Values.global.downloadsPath }}
            type: Directory
        - name: config
          hostPath:
            path: /var/lib/qbittorrent/config
            type: DirectoryOrCreate