apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: {{ .Values.namespace }}
  labels:
    app: qbittorrent
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.qbittorrent.webUiPort }}
      targetPort: {{ .Values.qbittorrent.webUiPort }}
      nodePort: {{ .Values.qbittorrent.webUiPort }}
      name: qbt-web
      protocol: TCP
  selector:
    app: qbittorrent