apiVersion: v1
kind: Service
metadata:
  name: byparr
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: byparr
  ports:
    - protocol: TCP
      port: 8191
      targetPort: 8191
  type: ClusterIP
