radarr_port: 7878
radarr_config: '{{ data_basepath }}/config/radarr'

prowlarr_port: 9696
prowlarr_config: '{{ data_basepath }}/config/prowlarr'

sonarr_port: 8989
sonarr_db_main: sonarr_main
sonarr_db_logs: sonarr_logs
sonarr_image: ghcr.io/onedr0p/sonarr:3.0.10
sonarr_config: '{{ data_basepath }}/config/sonarr'

flaresolverr_port: 39001

postgres_port: 5431
postgres_config: '{{ data_basepath }}/config/postgres'
postgres_password: postgres
postgres_user: postgres