{{- if .Values.plex.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "media-server.fullname" . }}-plex
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
    {{- include "media-server.componentLabels" "plex" | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "media-server.selectorLabels" . | nindent 6 }}
      {{- include "media-server.componentLabels" "plex" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "media-server.selectorLabels" . | nindent 8 }}
        {{- include "media-server.componentLabels" "plex" | nindent 8 }}
    spec:
      securityContext:
        {{- include "media-server.securityContext" . | nindent 8 }}
      containers:
      - name: plex
        image: {{ .Values.plex.image }}
        ports:
        - containerPort: {{ .Values.plex.port }}
          name: http
        - containerPort: 1900
          name: dlna-udp
          protocol: UDP
        - containerPort: 3005
          name: plex-companion
        - containerPort: 5353
          name: bonjour-udp
          protocol: UDP
        - containerPort: 8324
          name: plex-roku
        - containerPort: 32410
          name: gdm-32410
          protocol: UDP
        - containerPort: 32412
          name: gdm-32412
          protocol: UDP
        - containerPort: 32413
          name: gdm-32413
          protocol: UDP
        - containerPort: 32414
          name: gdm-32414
          protocol: UDP
        - containerPort: 32469
          name: dlna-tcp
        env:
        {{- include "media-server.commonEnv" . | nindent 8 }}
        - name: PLEX_CLAIM
          value: ""
        {{- if eq (.Values.plex.serviceType | default "NodePort") "LoadBalancer" }}
        - name: ADVERTISE_IP
          value: "http://{{ .Values.plex.externalIP | default "EXTERNAL_IP" }}:{{ .Values.plex.port }}"
        {{- else }}
        - name: ADVERTISE_IP
          value: "http://$(NODE_IP):{{ .Values.plex.nodePort }}"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        {{- end }}
        volumeMounts:
        {{- include "media-server.configVolumeMount" "plex" | nindent 8 }}
        {{- include "media-server.commonVolumeMounts" . | nindent 8 }}
        - name: dev-dri
          mountPath: /dev/dri
        resources:
          {{- toYaml .Values.plex.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /identity
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /identity
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      {{- include "media-server.configVolume" (dict "root" . "component" "plex") | nindent 6 }}
      {{- include "media-server.commonVolumes" . | nindent 6 }}
      - name: dev-dri
        hostPath:
          path: /dev/dri
          type: Directory
{{- end }}