---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: {{ .Values.namespace }}
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chown -R 1001:1001 /config /transcode /data"]
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
            - name: media
              mountPath: /data
      containers:
        - name: plex
          image: {{ .Values.plex.image }}
          ports:
            - containerPort: 32400
              name: plex-web
              protocol: TCP
            - containerPort: 32410
              name: gdm-32410
              protocol: UDP
            - containerPort: 32412
              name: gdm-32412
              protocol: UDP
            - containerPort: 32413
              name: gdm-32413
              protocol: UDP
            - containerPort: 32414
              name: gdm-32414
              protocol: UDP
          env:
            - name: TZ
              value: Europe/Paris
            - name: ADVERTISE_IP
              value: {{ .Values.plex.advertiseIp }}
            - name: PLEX_UID
              value: "1001"
            - name: PLEX_GID
              value: "1001"
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
            - name: media
              mountPath: /data
            - name: dev-dri
              mountPath: /dev/dri
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "6Gi"
              cpu: "4000m"
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
      volumes:
        - name: config
          hostPath:
            path: /var/lib/plex/config
            type: DirectoryOrCreate
        - name: transcode
          hostPath:
            path: /var/lib/plex/transcode
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: {{ .Values.global.libraryPath }}
            type: Directory
        - name: dev-dri
          hostPath:
            path: /dev/dri