---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: {{ .Values.namespace }}
  labels:
    app: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: plex
          image: {{ .Values.plex.image }}
          ports:
            - containerPort: 32400
              name: plex-web
              protocol: TCP
            - containerPort: 32410
              name: gdm-32410
              protocol: UDP
            - containerPort: 32412
              name: gdm-32412
              protocol: UDP
            - containerPort: 32413
              name: gdm-32413
              protocol: UDP
            - containerPort: 32414
              name: gdm-32414
              protocol: UDP
          env:
            - name: TZ
              value: Europe/Paris
            - name: ADVERTISE_IP
              value: {{ .Values.plex.advertiseIp }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
            - name: media
              mountPath: /library
          resources:
            requests:
              gpu.intel.com/i915: "1"
            limits:
              gpu.intel.com/i915: "1"
      volumes:
        - name: config
          hostPath:
            path: /var/lib/plex/config
            type: DirectoryOrCreate
        - name: transcode
          hostPath:
            path: /var/lib/plex/transcode
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: {{ .Values.global.libraryPath }}
            type: Directory