---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: {{ .Values.namespace }}
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: gluetun
          image:  {{ .Values.gluetun.image }}
          securityContext:
            privileged: true
            capabilities:
              add: [ "NET_ADMIN" ]
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: FIREWALL_INPUT_PORTS
              value: {{ .Values.qbittorrent.webUiPort }}
            - name: SERVER_COUNTRIES
              value: "France"
            - name: VPN_SERVICE_PROVIDER
              value: "protonvpn"
            - name: DNS_KEEP_NAMESERVER
              value: "off"
            - name: DOT
              value: "off"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: protonvpn-credentials
                  key: PROTONVPN_PRIVATE_KEY
        - name: plex
          image: {{ .Values.plex.image }}
          ports:
            - containerPort: 32400
              name: plex-web
              protocol: TCP
            - containerPort: 32410
              name: gdm-32410
              protocol: UDP
            - containerPort: 32412
              name: gdm-32412
              protocol: UDP
            - containerPort: 32413
              name: gdm-32413
              protocol: UDP
            - containerPort: 32414
              name: gdm-32414
              protocol: UDP
          env:
            - name: TZ
              value: Europe/Paris
            - name: ADVERTISE_IP
              value: {{ .Values.plex.advertiseIp }}
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
            - name: media
              mountPath: /library
            - name: dev-dri
              mountPath: /dev/dri
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "2000m"
      volumes:
        - name: config
          hostPath:
            path: /var/lib/plex/config
            type: DirectoryOrCreate
        - name: transcode
          hostPath:
            path: /var/lib/plex/transcode
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: {{ .Values.global.libraryPath }}
            type: Directory
        - name: dev-dri
          hostPath:
            path: /dev/dri