{{- if .Values.plex.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "media-server.fullname" . }}-plex
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
    {{- include "media-server.componentLabels" "plex" | nindent 4 }}
spec:
  type: {{ .Values.plex.serviceType | default "NodePort" }}
  ports:
  - port: {{ .Values.plex.port }}
    targetPort: http
    {{- if eq (.Values.plex.serviceType | default "NodePort") "NodePort" }}
    nodePort: {{ .Values.plex.nodePort }}
    {{- end }}
    name: http
  - port: 1900
    targetPort: dlna-udp
    protocol: UDP
    name: dlna-udp
  - port: 3005
    targetPort: plex-companion
    name: plex-companion
  - port: 5353
    targetPort: bonjour-udp
    protocol: UDP
    name: bonjour-udp
  - port: 8324
    targetPort: plex-roku
    name: plex-roku
  - port: 32410
    targetPort: gdm-32410
    protocol: UDP
    name: gdm-32410
  - port: 32412
    targetPort: gdm-32412
    protocol: UDP
    name: gdm-32412
  - port: 32413
    targetPort: gdm-32413
    protocol: UDP
    name: gdm-32413
  - port: 32414
    targetPort: gdm-32414
    protocol: UDP
    name: gdm-32414
  - port: 32469
    targetPort: dlna-tcp
    name: dlna-tcp
  selector:
    {{- include "media-server.selectorLabels" . | nindent 4 }}
    {{- include "media-server.componentLabels" "plex" | nindent 4 }}
{{- end }}