apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app: plex
spec:
  type: NodePort
  ports:
    - port: 32400
      targetPort: 32400
      nodePort: 32400
      name: plex-web
      protocol: TCP
    - port: 32410
      targetPort: 32410
      nodePort: 32410
      name: gdm-32410
      protocol: UDP
    - port: 32412
      targetPort: 32412
      nodePort: 32412
      name: gdm-32412
      protocol: UDP
    - port: 32413
      targetPort: 32413
      nodePort: 32413
      protocol: UDP
    - port: 32414
      targetPort: 32414
      nodePort: 32414
      name: gdm-32414
      protocol: UDP
  selector:
    app: plex