apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-manager
  labels:
    app: media-manager
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-manager
  template:
    metadata:
      name: media-manager
      labels:
        app: media-manager
    spec:
      containers:
        - name: media-manager
          image: {{ .Values.mediaManager.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP

      restartPolicy: Always
      