apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-manager
  labels:
    app: media-manager
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-manager
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/medias/config.yaml") . | sha256sum }}
      name: media-manager
      labels:
        app: media-manager
    spec:
      enableServiceLinks: false
      containers:
        - name: media-manager
          image: {{ .Values.mediaManager.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: CONFIG_DIR
              value: /config
            - name: TORRENTS__QBITTORRENT__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qbittorrent-secret
                  key: PASSWORD
            - name: TORRENTS__QBITTORRENT__USERNAME
              valueFrom:
                secretKeyRef:
                  name: qbittorrent-secret
                  key: USERNAME
            - name: DATABASE__USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: postgres-secret
            - name: DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
            - name: AUTH__TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: media-manager-secret
                  key: TOKEN_SECRET
            - name: INDEXERS__PROWLARR__API_KEY
              valueFrom:
                secretKeyRef:
                  name: prowlarr-secret
                  key: API_KEY
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data/tvshows
              name: library
              subPath: tvshows
            - mountPath: /data/movies
              name: library
              subPath: movies
            - mountPath: /data/torrents
              name: torrents
            - mountPath: /app/data/images
              name: images
      volumes:
        - name: library
          hostPath:
            path: {{ .Values.global.libraryPath }}
        - name: images
          hostPath:
            path: /var/lib/media-manager/images
            type: DirectoryOrCreate
        - name: config
          configMap:
            name: media-manager-config
            items:
              - key: config.toml
                path: config.toml
        - name: torrents
          hostPath:
            path: {{ .Values.global.downloadsPath }}
      