apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-manager-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 2h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
    namespace: external-secrets
  target:
    name: media-manager-secret
    creationPolicy: Owner
  data:
    - secretKey: TOKEN_SECRET
      remoteRef:
        key: /media-manager/TOKEN_SECRET