{{- if .Values.postgresql.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: SecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: /database/POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: /database/POSTGRES_PASSWORD
  - secretKey: POSTGRES_DB
    remoteRef:
      key: /database/POSTGRES_DB
{{- end }}