{{- if and .Values.prowlarr.enabled .Values.prowlarr.useExternalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-credentials-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: SecretStore
  target:
    name: prowlarr-credentials
    creationPolicy: Owner
  data:
  - secretKey: PROWLARR_API_KEY
    remoteRef:
      key: /prowlarr/API_KEY
{{- end }}