apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infisical-secret-store
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com/api
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-auth
            key: clientId
          clientSecret:
            name: infisical-auth
            key: clientSecret
      secretsScope:
        projectSlug: {{ .Values.infisical.projectId }}
        environmentSlug: {{ .Values.infisical.environment }}
        secretsPath: /