apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: amstram-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 2h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: amstram-secret
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: /amstram/GITHUB_TOKEN
