---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-server
  namespace: flux-system
spec:
  interval: 1h
  path: ./clusters/media-server/media-server
  prune: true
  wait: true
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system