---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "media-server.fullname" . }}-configarr-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
    {{- include "media-server.componentLabels" "configarr" | nindent 4 }}
data:
  config.yml: |
    trashGuideUrl: https://github.com/TRaSH-Guides/Guides
    recyclarrConfigUrl: https://github.com/recyclarr/config-templates

    sonarr:
      series:
        base_url: http://{{ include "media-server.fullname" . }}-sonarr:{{ .Values.sonarr.port }}
        api_key: !secret SONARR_API_KEY

        quality_definition:
          type: series

        # Delete old custom formats before applying new ones
        delete_old_custom_formats: true

        include:
          # Quality definitions
          - template: sonarr-quality-definition-series
          
          # WEB-1080p profile and formats
          - template: sonarr-v4-quality-profile-web-1080p
          - template: sonarr-v4-custom-formats-web-1080p

          # WEB-2160p profile and formats  
          - template: sonarr-v4-quality-profile-web-2160p
          - template: sonarr-v4-custom-formats-web-2160p

        custom_formats:
          # HDR/DV Custom Formats with your specified scores
          - trash_ids:
              - c53085ddbd027d9624b320627748612f # DV HDR10+
              - e23edd2482476e595fb990b12e7c609c # DV HDR10
              - 58d6a88f13e2db7f5059c41047876f00 # DV
              - 55d53828b9d81cbe20b02efd00aa0efd # DV HLG
              - a3e19f8f627608af0211acd02bf89735 # DV SDR
            assign_scores_to:
              - name: "WEB-1080p"
                score: 1500
              - name: "WEB-2160p"
                score: 1500

          - trash_ids:
              - b974a6cd08c1066250f1f177d7aa1225 # HDR10+
            assign_scores_to:
              - name: "WEB-1080p"
                score: 600
              - name: "WEB-2160p"
                score: 600

          - trash_ids:
              - dfb86d5941bc9075d6af23b09c2aeecd # HDR10
              - e61e28db95d22bedcadf030b8f156d96 # HDR
              - 2a4d9069cc1fe3242ff9bdaebed239bb # HDR (undefined)
              - 08d6d8834ad9ec87b1dc7ec8148e7a1f # PQ
              - 9364dd386c9b4a1100dde8264690add7 # HLG
            assign_scores_to:
              - name: "WEB-1080p"
                score: 500
              - name: "WEB-2160p"
                score: 500

          # Negative scoring formats
          - trash_ids:
              - ed38b889b31be83fda192888e2286d83 # BR-DISK
              - e6886871085226c3da1830830146846c # Generated Dynamic HDR
              - 90a6f9a284dff5103f6346090e6280c8 # LQ
              - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
              - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
              - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
              - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
              - 0a3f082873eb454bde444150b70253cc # Extras
              - 712d74cd88bceb883ee32f773656b1f5 # Sing-Along Versions
              - cae4ca30163749b891686f95532519bd # AV1
              - d6e9318c875905d6cfb5bee961afcea9 # Language: Not Original
            assign_scores_to:
              - name: "WEB-1080p"
                score: -10000
              - name: "WEB-2160p"
                score: -10000

          # Language preferences
          - trash_ids:
              - 9172b2f683f6223e3a1846427b417a3d # VOSTFR
            assign_scores_to:
              - name: "WEB-1080p"
                score: 1000
              - name: "WEB-2160p"
                score: 1000
          - trash_ids:
              - d6e9318c875905d6cfb5bee961afcea9 # Not Original
            assign_scores_to:
              - name: "WEB-1080p"
                score: -10000
              - name: "WEB-2160p"
                score: -10000
          - trash_ids:
              - 0542a48746585dc4444bbbb8a6bdf6ea # Original + French
            assign_scores_to:
              - name: "WEB-1080p"
                score: 500
              - name: "WEB-2160p"
                score: 500

    radarr:
      movies:
        base_url: http://{{ include "media-server.fullname" . }}-radarr:{{ .Values.radarr.port }}
        api_key: !secret RADARR_API_KEY

        quality_definition:
          type: movie

        include:
          # WEB-1080p
          - template: radarr-quality-definition-movie
          - template: radarr-quality-profile-web-1080p
          - template: radarr-custom-formats-web-1080p

          # WEB-2160p
          - template: radarr-quality-profile-web-2160p
          - template: radarr-custom-formats-web-2160p

        custom_formats:
          # HDR/DV Custom Formats with your specified scores
          - trash_ids:
              - c53085ddbd027d9624b320627748612f # DV HDR10+
              - e23edd2482476e595fb990b12e7c609c # DV HDR10
              - 58d6a88f13e2db7f5059c41047876f00 # DV
              - 55d53828b9d81cbe20b02efd00aa0efd # DV HLG
              - a3e19f8f627608af0211acd02bf89735 # DV SDR
            assign_scores_to:
              - name: "WEB-1080p"
                score: 1500
              - name: "WEB-2160p"
                score: 1500

          - trash_ids:
              - b974a6cd08c1066250f1f177d7aa1225 # HDR10+
            assign_scores_to:
              - name: "WEB-1080p"
                score: 600
              - name: "WEB-2160p"
                score: 600

          - trash_ids:
              - dfb86d5941bc9075d6af23b09c2aeecd # HDR10
              - e61e28db95d22bedcadf030b8f156d96 # HDR
              - 2a4d9069cc1fe3242ff9bdaebed239bb # HDR (undefined)
              - 08d6d8834ad9ec87b1dc7ec8148e7a1f # PQ
              - 9364dd386c9b4a1100dde8264690add7 # HLG
            assign_scores_to:
              - name: "WEB-1080p"
                score: 500
              - name: "WEB-2160p"
                score: 500

          # Movie-specific quality formats
          - trash_ids:
              - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos
              - 2f22d89048b01681dde8afe73aabb0b9 # DTS-X
              - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
              - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
              - 3cafb66171b47f226146a0770576870f # TrueHD
              - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
              - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
              - e7c2fcae07cbada050a0af3357491d7b # PCM
            assign_scores_to:
              - name: "WEB-1080p"
                score: 250
              - name: "WEB-2160p"
                score: 250

          # Negative scoring formats
          - trash_ids:
              - ed38b889b31be83fda192888e2286d83 # BR-DISK
              - e6886871085226c3da1830830146846c # Generated Dynamic HDR
              - 90a6f9a284dff5103f6346090e6280c8 # LQ
              - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
              - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
              - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
              - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
              - 0a3f082873eb454bde444150b70253cc # Extras
              - cae4ca30163749b891686f95532519bd # AV1
              - d6e9318c875905d6cfb5bee961afcea9 # Language: Not Original
            assign_scores_to:
              - name: "WEB-1080p"
                score: -10000
              - name: "WEB-2160p"
                score: -10000

          # Language preferences (same as Sonarr)
          - trash_ids:
              - 9172b2f683f6223e3a1846427b417a3d # VOSTFR
            assign_scores_to:
              - name: "WEB-1080p"
                score: 1000
              - name: "WEB-2160p"
                score: 1000
          - trash_ids:
              - d6e9318c875905d6cfb5bee961afcea9 # Not Original
            assign_scores_to:
              - name: "WEB-1080p"
                score: -10000
              - name: "WEB-2160p"
                score: -10000
          - trash_ids:
              - 0542a48746585dc4444bbbb8a6bdf6ea # Original + French
            assign_scores_to:
              - name: "WEB-1080p"
                score: 500
              - name: "WEB-2160p"
                score: 500
    prowlarr:
      indexers:
        base_url: http://{{ include "media-server.fullname" . }}-prowlarr:{{ .Values.prowlarr.port }}
        api_key: !secret PROWLARR_API_KEY

        # Prowlarr doesn't use templates like Sonarr/Radarr
        # Configuration is mainly done through the web interface
        # Configarr can be used to sync indexers to Sonarr/Radarr