- name: Allow rule - TCP
  become: true
  tags:
    - become
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
     - 32400
     - 32469
     - 8324

- name: Allow rule - UDP
  become: true
  tags:
    - become
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: udp
  loop:
    - 1900
    - 3005
    - 5353
    - 32410
    - 32412
    - 32413
    - 32414
    - 32469