{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "media-server.fullname" . }}-postgresql-init
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
    {{- include "media-server.componentLabels" "postgresql" | nindent 4 }}
data:
  01-create-databases.sql: |
    -- Create databases for Sonarr
    CREATE DATABASE {{ .Values.sonarr.database.main }};
    CREATE DATABASE {{ .Values.sonarr.database.logs }};
    
    -- Create databases for Radarr
    CREATE DATABASE {{ .Values.radarr.database.main }};
    CREATE DATABASE {{ .Values.radarr.database.logs }};
    
    -- Grant permissions
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.sonarr.database.main }} TO {{ "\"${POSTGRES_USER}\"" }};
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.sonarr.database.logs }} TO {{ "\"${POSTGRES_USER}\"" }};
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.radarr.database.main }} TO {{ "\"${POSTGRES_USER}\"" }};
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.radarr.database.logs }} TO {{ "\"${POSTGRES_USER}\"" }};
{{- end }}